### ISSUE TITLE
Theme CSS can conflict with documented CSS

### ISSUE THREAD

**Issue by davidtheclark** [documentationjs/styledoc#4]
Here's an interesting fundamental problem of a CSS documentation generator: the theme CSS can conflict with the CSS that you're documenting, result in one or the other or both becoming wonky.

I'm thinking maybe the documentation theme should rely entirely on inline styles.

**Comment by samanpwbb** [comment]
styling the theme with scoped classes seems better to me. If necessary, combine with some trick to increase the specificity, like `!important` on every property or ids instead of classes?

**Comment by davidtheclark** [comment]
Yeah, the current system we're trying uses scoped classes, allowing theme CSS to override as necessary, with `!important` or some other method. So I'll close this.
